### ISSUE TITLE
CLI on Macos does not have write permissions

### ISSUE THREAD

**Issue by pnealgit** [Lux-AI-Challenge/Lux-Design-2021#132]
Hi,
It seems when I try to run anything on my Mac, I get write access errors. 
It does not seem to be writing to the local directory , in this case /Users/pneal/lux

It also gets write access refused when trying to do a simple:
lux-ai-2021 --statefulReplay

Is there a way to designate where log and replay files should go ?

Phillips-MacBook-Air:lux pneal$ lux-ai-2021 agent.py agent.py
internal/fs/utils.js:314
    throw err;
    ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@lux-ai/2021-challenge/node_modules/local/bots'
    at Object.mkdirSync (fs.js:1009:3)
    at new Dimension (/usr/local/lib/node_modules/@lux-ai/2021-challenge/node_modules/dimensions-ai/lib/main/Dimension/index.js:217:18)
    at Object.create (/usr/local/lib/node_modules/@lux-ai/2021-challenge/node_modules/dimensions-ai/lib/main/Dimension/index.js:491:12)
    at Object.runner (/usr/local/lib/node_modules/@lux-ai/2021-challenge/lib/es5/bin/runner.js:78:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/@lux-ai/2021-challenge/lib/es5/bin/index.js:92:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/local/lib/node_modules/@lux-ai/2021-challenge/node_modules/local/bots'
}
Phillips-MacBook-Air:lux pneal$

**Comment by StoneT2000** [comment]
The tool generates some other files within the package itself for various purposes (eg caching when running tournament mode although it's useless in the local case)

Try running with sudo

**Comment by pnealgit** [comment]
I do not like running anything as sudo.

**Comment by StoneT2000** [comment]
Ok instead of a global install, make a folder and inside it do `npm install @lux-ai/2021-challenge`

Then try running

`npx lux-ai-2021` as the command add your arguments`

**Comment by pnealgit** [comment]
Hi Stone,
npx did the trick. But now I have a release mis-match between the 3.0
visualizer and the 3.1 replay.json
code.... I think.

Best regards,
Phil

**Comment by pnealgit** [comment]
Hi Stone,
To get 3.1 I had to say:
npm install @***@***.***

(added on the ***@***.***' )

Phil

**Comment by pnealgit** [comment]
Dang ! I should have written:

 npm install @***@***.***

**Comment by StoneT2000** [comment]
Sorry not sure what you are typing, I just see ****, is this issue resolved?

**Comment by pnealgit** [comment]
Hi Stone,

I didn't send any '****' . Hmmm

But I did get the 3.1 dist.zip, installed it , and now everything is
working fine.
(Except maybe for my brain.)
Yes. The issue is resolved.

Thank you for your efforts.
Phil
